{
  "formatVersion": "1.1",
  "component": {
    "group": "com.btwrobotics.whattime.frc",
    "module": "whattime",
    "version": "v2026.1.16-beta.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whattime-v2026.1.16-beta.9.jar",
          "url": "whattime-v2026.1.16-beta.9.jar",
          "size": 20637,
          "sha512": "8abbb8e9c8817f9770eea55ff1e77cf023ae0f7be664d07926964b8a7bcf1d16749bfe0ea57cf124bcd531c20fd9c54bfa429da664868ac4cbaa0de733052c87",
          "sha256": "8cba2c9d489f55198a1897fcbc99d24afcace297f9452ed4254558f73309975f",
          "sha1": "47f539150a69902e2470f22b7daa9cd6936224f3",
          "md5": "652fc8eaf4430134f11e86d5c27d7ce4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "whattime-v2026.1.16-beta.9.jar",
          "url": "whattime-v2026.1.16-beta.9.jar",
          "size": 20637,
          "sha512": "8abbb8e9c8817f9770eea55ff1e77cf023ae0f7be664d07926964b8a7bcf1d16749bfe0ea57cf124bcd531c20fd9c54bfa429da664868ac4cbaa0de733052c87",
          "sha256": "8cba2c9d489f55198a1897fcbc99d24afcace297f9452ed4254558f73309975f",
          "sha1": "47f539150a69902e2470f22b7daa9cd6936224f3",
          "md5": "652fc8eaf4430134f11e86d5c27d7ce4"
        }
      ]
    }
  ]
}
